controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Parser;
use app\models\tests\SiteTest;
use app\models\ExcelExport;

class SiteController extends Controller {

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $model = new Parser(['uri' => '/robots.txt']);
        if ($model->load(Yii::$app->request->post())) {
            $model->exec();
            $siteTest = new SiteTest(['content' => $model->content, 'statusCode' => $model->statusCode]);
            $summary = $siteTest->exec();
            Yii::$app->session->set('summary', serialize($summary));
            return $this->render('index', ['model' => $model, 'summary' => $summary]);
        }
        return $this->render('index', ['model' => $model]);
    }

    public function actionSave() {
        if (($summary = unserialize(Yii::$app->session->get('summary')))) {
            (new ExcelExport(['summary' => $summary]))->export();
            Yii::$app->response->sendFile('export.xls')->send();
        }
    }

}

views/site/_item.php
<tr>
    <td style="border:2px solid #cccccc;" colspan=5 height="21" align="left" valign=bottom bgcolor="#EFEFEF"><font face="Arial" color="#000000"><br></font></td>
</tr>

<tr>
    <td style="border:2px solid #cccccc;" rowspan=2 height="106" align="center" valign=middle sdval="12" sdnum="1033;"><font face="Arial" color="#000000"><?= $index ?></font></td>
    <td style="border:2px solid #cccccc;" rowspan=2 align="left" valign=middle><font face="Arial" color="#000000"><?= $model['name'] ?></font></td>
    <td style="border:2px solid #cccccc;" rowspan=2 align="center" valign=middle bgcolor="<?= $model['status'] == 'Ок' ? '#00FF00' : '#E06666' ?>"><font face="Arial" color="#000000"><?= $model['status'] ?></font></td>
    <td style="border:2px solid #cccccc;" align="left" valign=middle><font face="Arial" color="#000000">Состояние</font></td>
    <td style="border:2px solid #cccccc;" align="left" valign=bottom><font face="Arial" color="#000000"><?= $model['state'] ?></font></td>
</tr>
<tr>
    <td style="border:2px solid #cccccc;" align="left" valign=middle><font face="Arial" color="#000000">Рекомендации</font></td>
    <td style="border:2px solid #cccccc;" align="left" valign=bottom><font face="Arial" color="#000000"><?= $model['recommends'] ?></font></td>
</tr>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
$this->title = 'Site checker';
?>
<style type="text/css">
    table,thead,tbody,tfoot,tr,th,td { font-family:"Calibri"; font-size:x-small }
    a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
    a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
    comment { display:none;  } 
    td{
        text-align: center;
        vertical-align: middle;
    }
    .table{
        margin-top: 10px;
    }
</style>

<div class="site-index">    
    <?php $form = ActiveForm::begin() ?>

    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3 col-sm-offset-3">
            <?= $form->field($model, 'host') ?>
            <?= Html::submitButton('Проверить', ['class' => 'btn btn-success']) ?>
            <?php if (isset($summary)): ?>
                <?= Html::a('Сохранить', ['site/save'], ['class' => 'btn btn-primary']) ?>
            <?php endif; ?>
        </div>
    </div>
    <?php if (isset($summary)): ?>
        <div class="table" id="table">
            <table cellspacing="0" border="0">
                <colgroup width="64"></colgroup>
                <colgroup width="396"></colgroup>
                <colgroup width="90"></colgroup>
                <colgroup width="112"></colgroup>
                <colgroup width="486"></colgroup>
                <tr>
                    <td style="border-top: 2px solid #cccccc; border-bottom: 2px solid #cccccc; border-left: 2px solid #cccccc; border-right: 2px solid #cccccc" height="21" align="center" valign=middle bgcolor="#A2C4C9"><b><font face="Arial" color="#000000">№</font></b></td>
                    <td style="border-top: 2px solid #cccccc; border-bottom: 2px solid #cccccc; border-left: 2px solid #cccccc; border-right: 2px solid #cccccc" align="left" valign=middle bgcolor="#A2C4C9"><b><font face="Arial" color="#000000">Название проверки</font></b></td>
                    <td style="border-top: 2px solid #cccccc; border-bottom: 2px solid #cccccc; border-left: 2px solid #cccccc; border-right: 2px solid #cccccc" align="center" valign=bottom bgcolor="#A2C4C9"><b><font face="Arial" color="#000000">Статус</font></b></td>
                    <td style="border-top: 2px solid #cccccc; border-bottom: 2px solid #cccccc; border-left: 2px solid #cccccc; border-right: 2px solid #cccccc" align="left" valign=bottom bgcolor="#A2C4C9"><font face="Arial" color="#000000"><br></font></td>
                    <td style="border-top: 2px solid #cccccc; border-bottom: 2px solid #cccccc; border-left: 2px solid #cccccc; border-right: 2px solid #cccccc" align="left" valign=bottom bgcolor="#A2C4C9"><b><font face="Arial" color="#000000">Текущее состояние</font></b></td>
                </tr>

                <?php foreach ($summary as $index => $item): ?>
                    <?= $this->render('_item', ['model' => $item, 'index' => $index + 1]) ?>
                <?php endforeach; ?>
            </table>

        </div>
    <?php endif;
    ?>
    <?php ActiveForm::end(); ?>
</div>